spring.application.name=pertamuan11

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Thymeleaf Configuration
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Datasource (H2 in-memory)
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Server Configuration
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.deploy.pertamuan11=DEBUG

